### ISSUE TITLE
Trying to use the API for the first time: SERVER_ERROR

### ISSUE THREAD

**Issue by narthur** [robbietjuh/py-bricklink#6]
The two commands I've tried so far:

    api.catalog.getItem(item_no=30153)
    api.catalog.getPriceGuide(item_type='SET', item_no='colsim-2', guide_type='sold', new_or_used='N')

And the error I get:

```
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    stat = pr.api.catalog.getPriceGuide(item_type='SET', item_no='colsim-2', guide_type='sold', new_or_used='N')
  File "/home/nathan/ProgrammingProjects/bricklink-tools/bricklink/methods.py", line 189, in getPriceGuide
    return self.client.get(self.URL_CATALOG_PRICE_GUIDE.format(type=item_type, no=item_no), params)
  File "/home/nathan/ProgrammingProjects/bricklink-tools/bricklink/api.py", line 63, in get
    return self.request('GET', url, params)
  File "/home/nathan/ProgrammingProjects/bricklink-tools/bricklink/api.py", line 60, in request
    return self.processResponse(response, method, url, params)
  File "/home/nathan/ProgrammingProjects/bricklink-tools/bricklink/api.py", line 42, in processResponse
    elif meta['message'] == 'BAD_OAUTH_REQUEST': raise BricklinkBadOauthRequestException(meta['description'])
bricklink.exceptions.BricklinkBadOauthRequestException: SERVER_ERROR: Server Error
```

I've searched the Internet to try to figure it out, but can't find anyone talking about this specific error.

Thanks for making this tool available!

**Comment by robbietjuh** [comment]
It seems that you are missing the `color_id` attribute. If I recall correctly, that attribute is required by the BrickLink API.

You may specify `color_id=0` for sets. That'll correspond to the 'Not Applicable' color.

Did this fix your problem or have you yet found another solution?
